all:
  children:
    clickhouse_group:
      hosts:
        clickhouse:
          ansible_host: 51.250.92.177
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/ansible/ansible-03/sshkey
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    lighthouse_group:
      hosts:
        lighthouse:
          ansible_host: 158.160.106.112
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/ansible/ansible-03/sshkey
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    vector_group:
      hosts:
        vector:
          ansible_host: 158.160.103.134
          ansible_user: v3ll
          ansible_ssh_private_key_file: /root/ansible/ansible-03/sshkey
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  