---
- name: Deploy ClickHouse
  hosts: clickhouse_group
  become: true
  roles:
    - clickhouse

- name: Deploy Vector
  hosts: vector_group
  become: true
  roles:
    - vector-role

- name: Deploy LightHouse
  hosts: lighthouse_group
  become: true
  roles:
    - lighthouse-role