#cloud-config
users:
  - name: v3ll
    groups: sudo
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh-authorized-keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: true
