- name: Install curl
  ansible.builtin.apt:
    name:
      - curl
    state: present
    update_cache: yes

- name: Script detects platform and installs Vector
  shell: curl --proto '=https' --tlsv1.2 -sSfL https://sh.vector.dev | bash -s -- -y

- name: Create directory for Vector configuration
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    mode: '0755'

- name: Copy Vector configuration
  ansible.builtin.template:
    src: /root/ansible/ansible-03/playbook/templates/vector_conf.j2
    dest: /etc/vector/vector.yaml
    owner: root
    group: root
    mode: '0644'

- name: Create database for logs
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0